spring:
  application:
    name: daily-report-backend

  # PostgreSQL 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/daily_report
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  # devtools 설정
  devtools:
    restart:
      enabled: false
  # Jackson 설정 (JSON 직렬화/역직렬화)
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss

# JWT 설정
jwt:
  secret: ${JWT_SECRET} # 환경변수로 분리
  expiration: 31536000000 # 1년 (365일 * 24시간 * 60분 * 60초 * 1000밀리초)

# 로깅 설정
logging:
  level:
    com.dailyreport.backend: DEBUG
    com.ai.dailyReport: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /v1
