name: EMS Deploy
run-name: "EMS Deploy 🚀 [ ${{ github.actor }} - ${{ github.ref_name }} - ${{ github.event.head_commit.message }} ]"

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    if: github.ref_name == 'main'
    runs-on: daily-report-01
    env:
      REMOTE_PATH: /home/daily-report
      JAR_NAME: daily-report-0.0.1-SNAPSHOT.jar

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Build Project
        run: |
          set -e
          chmod +x gradlew
          ./gradlew clean build

      - name: Copy JAR to PROD Path
        run: |
          set -e
          LOCAL_JAR="./build/libs/${JAR_NAME}"
          cp "$LOCAL_JAR" "$REMOTE_PATH/$JAR_NAME"

      - name: Restart PROD Service
        run: |
          set -e
          cd "$REMOTE_PATH"
          cp "$JAR_NAME" "$JAR_NAME.bak" || true
          ./restart.sh || echo "restart.sh exited with non-zero code."
